FROM quay.io/centos/centos:stream9 AS builder
ARG APP_ROOT=/opt/app-root/src
WORKDIR $APP_ROOT
RUN dnf install -y git golang && dnf clean all
#ENV GOPATH=$APP_ROOT
COPY . .
RUN make _build-manager BIN_PATH=.

FROM quay.io/centos/centos:stream9
COPY --from=builder /opt/app-root/src/manager /usr/bin/sriov-network-operator
COPY bindata /bindata
ENV OPERATOR_NAME=sriov-network-operator
ENTRYPOINT ["/usr/bin/sriov-network-operator"]
