# Workflow that performs builds of k8snetworkplumbingwg/sriov-network-operator images
# The images are also pushed to quay.io if it's not a pull request

name: Multi-arch and multi-distro build for sriov-network-* container images
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        container: [ operator, config-daemon, webhook ]
        distro-name: [ centos-stream ]
        distro-version: [ 9 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository for the Dockerfiles
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        if: github.event_name == 'pull_request'
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ${{ matrix.distro-name }}/${{ matrix.distro-version }}/Dockerfile.${{ matrix.container }}
          failure-threshold: error

      - name: Checkout k8snetworkplumbingwg/sriov-network-operator for the code
        uses: actions/checkout@v2
        with:
          repository: k8snetworkplumbingwg/sriov-network-operator
          path: sriov-network-operator

      - name: Build the ${{ matrix.container }} image for ${{ matrix.distro-name }}-${{ matrix.distro-version }}
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: sriov-network-${{ matrix.container }}
          tags: "${{ matrix.distro-name }}-${{ matrix.distro-version }}"
          containerfiles: |
            ./${{ matrix.distro-name }}/${{ matrix.distro-version }}/Dockerfile.${{ matrix.container }}
          context: sriov-network-operator

      - name: List container images
        run: docker images

      - name: Scan the ${{ matrix.container }} image for ${{ matrix.distro-name }}-${{ matrix.distro-version }} with Anchore
        id: scan-image
        uses: anchore/scan-action@v3
        with:
          image: sriov-network-${{ matrix.container }}:${{ matrix.distro-name }}-${{ matrix.distro-version }}

      - name: Push the ${{ matrix.container }} image for ${{ matrix.distro-name }}-${{ matrix.distro-version }} to Quay.io
        id: push-to-quay
        if: |
          github.event_name == 'schedule' ||
          (
            ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) &&
            ( github.ref == 'refs/head/main' || startsWith(github.ref, 'refs/head/release' ))
          )
        uses: redhat-actions/push-to-registry@v2
        with:
          image: sriov-network-${{ matrix.container }}
          tags: "${{ matrix.distro-name }}-${{ matrix.distro-version }}"
          registry: quay.io/rh-ecosystem-edge
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

